### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by gkmk** [gkmk/project-a#2]
- Name (basket, footbal...)

User link to activity
- Skill Level (new, beginner, intermediate, advanced, pro)
- Dates Available (select day from week)
- Times Available (morning, noon, evening)

**Comment by Biancanikolov** [comment]
Soccer (Football)
Basketball
Baseball
Tennis
Volleyball
Swimming
Cycling
Running
Golf
Rugby
Hockey
Badminton
Table Tennis (Ping Pong)
Skiing
Snowboarding
Martial Arts (e.g., Karate, Judo)
Boxing
Wrestling
Lacrosse
Rowing
Surfing
Rock Climbing
Gymnastics
Track and Field (Athletics)
Fencing
